# Generated by Django 3.2.8 on 2021-10-23 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistprofile',
            old_name='artistName',
            new_name='artisticName',
        ),
    ]
