# Generated by Django 3.2.7 on 2021-10-03 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatoGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numLikes', models.IntegerField(default=0)),
                ('numReproducciones', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('archivoSonido', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('formatogeneral_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Musica.formatogeneral')),
                ('caratura', models.ImageField(upload_to='')),
                ('fechaLanzamiento', models.DateField()),
            ],
            bases=('Musica.formatogeneral',),
        ),
        migrations.CreateModel(
            name='ListaReproduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pistas', models.ManyToManyField(to='Musica.Pista')),
                ('usuarioCreador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreArtistico', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='pista',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Musica.album'),
        ),
        migrations.AddField(
            model_name='album',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Musica.artista'),
        ),
    ]
