# Generated by Django 3.2.7 on 2021-10-04 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numLikes', models.IntegerField(default=0)),
                ('numReproducciones', models.IntegerField(default=0)),
                ('caratura', models.ImageField(upload_to='')),
                ('fechaLanzamiento', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListaReproduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SeguidorLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listaReproduccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Musica.listareproduccion')),
                ('seguidores', models.ManyToManyField(to='Usuarios.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Pista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numLikes', models.IntegerField(default=0)),
                ('numReproducciones', models.IntegerField(default=0)),
                ('archivoSonido', models.FileField(upload_to='')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Musica.album')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='listareproduccion',
            name='pistas',
            field=models.ManyToManyField(to='Musica.Pista'),
        ),
        migrations.AddField(
            model_name='listareproduccion',
            name='usuarioCreador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario'),
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreArtistico', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Musica.artista'),
        ),
    ]
