# Generated by Django 3.2.7 on 2021-10-07 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('numLikes', models.IntegerField(default=0)),
                ('numReproductions', models.IntegerField(default=0)),
                ('cover', models.ImageField(upload_to='')),
                ('releaseDate', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ListaReproduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SeguidorLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.ManyToManyField(to='Usuarios.Perfil')),
                ('playList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Musica.listareproduccion')),
            ],
        ),
        migrations.CreateModel(
            name='Pista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('numLikes', models.IntegerField(default=0)),
                ('numReproductions', models.IntegerField(default=0)),
                ('soundFile', models.FileField(upload_to='')),
                ('releaseDate', models.DateField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Musica.album')),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Musica.genero')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='listareproduccion',
            name='tracks',
            field=models.ManyToManyField(to='Musica.Pista'),
        ),
        migrations.AddField(
            model_name='listareproduccion',
            name='usuarioCreador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.perfil'),
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artisticName', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.perfil')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Musica.artista'),
        ),
    ]
