# Generated by Django 3.2.7 on 2021-10-08 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musica', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genero',
            old_name='nombre',
            new_name='name',
        ),
    ]
